-- ============================================
-- Prophet Predict Table Migration
-- ============================================
-- Creates table for salinity forecast data from Prophet model
-- Public read access enabled for research purposes
-- ============================================

-- Create the prophet_predict table
CREATE TABLE IF NOT EXISTS public.prophet_predict (
    id BIGSERIAL PRIMARY KEY,
    nam SMALLINT NOT NULL CHECK (nam >= 2024 AND nam <= 2050),
    tinh VARCHAR(255) NOT NULL,
    ten_tram VARCHAR(255) NOT NULL,
    lon NUMERIC(10, 6) NOT NULL CHECK (lon >= -180 AND lon <= 180),
    lat NUMERIC(10, 6) NOT NULL CHECK (lat >= -90 AND lat <= 90),
    du_bao_man NUMERIC(10, 2) NOT NULL CHECK (du_bao_man >= 0),
    lower_ci NUMERIC(10, 2) NOT NULL,
    upper_ci NUMERIC(10, 2) NOT NULL,
    he_so_vi_tri NUMERIC(5, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT check_ci_order CHECK (lower_ci <= du_bao_man AND du_bao_man <= upper_ci)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_prophet_predict_nam ON public.prophet_predict(nam);
CREATE INDEX IF NOT EXISTS idx_prophet_predict_tinh ON public.prophet_predict(tinh);
CREATE INDEX IF NOT EXISTS idx_prophet_predict_ten_tram ON public.prophet_predict(ten_tram);
CREATE INDEX IF NOT EXISTS idx_prophet_predict_location ON public.prophet_predict(lat, lon);
CREATE INDEX IF NOT EXISTS idx_prophet_predict_created_at ON public.prophet_predict(created_at);

-- Create composite index for common queries
CREATE INDEX IF NOT EXISTS idx_prophet_predict_composite 
ON public.prophet_predict(nam, tinh, ten_tram);

-- Enable Row Level Security
ALTER TABLE public.prophet_predict ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Allow public read access" 
ON public.prophet_predict 
FOR SELECT 
TO public 
USING (true);

-- Create policy for authenticated insert (for data import)
CREATE POLICY "Allow authenticated insert" 
ON public.prophet_predict 
FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- Create policy for authenticated update (for data correction)
CREATE POLICY "Allow authenticated update" 
ON public.prophet_predict 
FOR UPDATE 
TO authenticated 
USING (true);

-- Add comments for documentation
COMMENT ON TABLE public.prophet_predict IS 'Salinity forecast data generated by Prophet model for scientific research';
COMMENT ON COLUMN public.prophet_predict.nam IS 'Forecast year (2024-2050)';
COMMENT ON COLUMN public.prophet_predict.tinh IS 'Province/City name';
COMMENT ON COLUMN public.prophet_predict.ten_tram IS 'Station name';
COMMENT ON COLUMN public.prophet_predict.lon IS 'Longitude coordinate';
COMMENT ON COLUMN public.prophet_predict.lat IS 'Latitude coordinate';
COMMENT ON COLUMN public.prophet_predict.du_bao_man IS 'Predicted salinity value (g/l)';
COMMENT ON COLUMN public.prophet_predict.lower_ci IS 'Lower bound of 95% confidence interval';
COMMENT ON COLUMN public.prophet_predict.upper_ci IS 'Upper bound of 95% confidence interval';
COMMENT ON COLUMN public.prophet_predict.he_so_vi_tri IS 'Location coefficient factor';

-- ============================================
-- Sample Data (Optional - for testing)
-- ============================================
-- Uncomment to insert sample data for testing

/*
INSERT INTO public.prophet_predict (nam, tinh, ten_tram, lon, lat, du_bao_man, lower_ci, upper_ci, he_so_vi_tri) VALUES
(2024, 'Cà Mau', 'Trạm Sông Đốc', 104.89, 9.28, 0.85, 0.65, 1.05, 1.20),
(2024, 'Cà Mau', 'Trạm Đầm Dơi', 105.12, 9.56, 1.24, 0.95, 1.53, 1.45),
(2024, 'Bạc Liêu', 'Trạm Bạc Liêu', 105.72, 9.29, 2.15, 1.75, 2.55, 1.85),
(2024, 'Sóc Trăng', 'Trạm Vĩnh Châu', 105.97, 9.33, 3.45, 2.95, 3.95, 2.15),
(2024, 'Trà Vinh', 'Trạm Duyên Hải', 106.42, 9.63, 4.25, 3.65, 4.85, 2.45),

(2025, 'Cà Mau', 'Trạm Sông Đốc', 104.89, 9.28, 0.92, 0.70, 1.14, 1.20),
(2025, 'Cà Mau', 'Trạm Đầm Dơi', 105.12, 9.56, 1.35, 1.05, 1.65, 1.45),
(2025, 'Bạc Liêu', 'Trạm Bạc Liêu', 105.72, 9.29, 2.28, 1.85, 2.71, 1.85),
(2025, 'Sóc Trăng', 'Trạm Vĩnh Châu', 105.97, 9.33, 3.65, 3.10, 4.20, 2.15),
(2025, 'Trà Vinh', 'Trạm Duyên Hải', 106.42, 9.63, 4.52, 3.85, 5.19, 2.45),

(2026, 'Cà Mau', 'Trạm Sông Đốc', 104.89, 9.28, 1.05, 0.82, 1.28, 1.20),
(2026, 'Cà Mau', 'Trạm Đầm Dơi', 105.12, 9.56, 1.48, 1.15, 1.81, 1.45),
(2026, 'Bạc Liêu', 'Trạm Bạc Liêu', 105.72, 9.29, 2.45, 1.98, 2.92, 1.85),
(2026, 'Sóc Trăng', 'Trạm Vĩnh Châu', 105.97, 9.33, 3.88, 3.28, 4.48, 2.15),
(2026, 'Trà Vinh', 'Trạm Duyên Hải', 106.42, 9.63, 4.85, 4.10, 5.60, 2.45);
*/
